### ISSUE TITLE
.pageでページ分割した際の不具合

### ISSUE THREAD

**Issue by Iruyan-Zak** [yamasy1549/ZinkeN#23]
.page記述の高さ(インデントの深さ)によって以下の不具合が発生する
- 1ページ目と同じ：h3以下のカウントがリセットされる
- １段深い：上記に加えて、２ページ目が右に寄る
- 2段深い：カウントは正常だが、さらに２ページ目が右に寄る

**Comment by yamasy1549** [comment]
たぶん v0.1.1 で解決した（？）

**Comment by yamasy1549** [comment]
カウント、直ってなかった…

**Comment by yamasy1549** [comment]
そもそも `.page` で分割するなということにしたので無理矢理解決
