### ISSUE TITLE
title とか authors とか変数にする必要はあったのか

### ISSUE THREAD

**Issue by yamasy1549** [yamasy1549/ZinkeN#27]
ないのでは

**Comment by Iruyan-Zak** [comment]
titleって、「PDFファイル/Webページのタイトル」と「紙面のタイトル」を兼ねてたりしないの
authorsは・・・PDFに署名したりしないなら別に必要ではないけれど、titlepageの要素として統一して変数としておいても良いんじゃないの

**Comment by yamasy1549** [comment]
今ね、複数のjadeファイルがあったときも同じtitleになっちゃってるの

**Comment by yamasy1549** [comment]
https://github.com/yamasy1549/ZinkeN/pull/28

とりあえず表紙に出てくる分のは直書きするようにしている

**Comment by Iruyan-Zak** [comment]
ZinkeNがデフォルトで提供するスタイルシート・mixinと、ユーザが自分で定義・編集するファイルってそもそもディレクトリ分けるべきな気がする

そしたら各プロジェクトの変数は混在しないし、変数定義もずっとわかりやすくなりそう

**Comment by yamasy1549** [comment]
わかる…

いまデフォルトで提供してるスタイルシートしかないから、別で「自分でカスタマイズする用」の空のスタイルシートを用意すればいい（？）

**Comment by Iruyan-Zak** [comment]
このissueではないような話をするので、提案を別のissueに切ってきます

**Comment by yamasy1549** [comment]
https://github.com/yamasy1549/ZinkeN/commit/1b4ee19f51a6d1f239eac6a177f2e1de600c356f
このcommitで変数をなくして直書きになってた
