### ISSUE TITLE
箇条書きリストの約物変更のマニュアル

### ISSUE THREAD

**Issue by Iruyan-Zak** [yamasy1549/ZinkeN#7]
多分デフォルトで約物は変わってくれるんでしょうけれど、ユーザが変えたいという時には変更できるようにやり方を提示してほしい感じがしないでもない

**Comment by yamasy1549** [comment]
Default:

![image](https://cloud.githubusercontent.com/assets/7820884/15096324/fb8cc8fc-152d-11e6-843d-800b412b7ba3.png)

ネスト3以降はおなじっぽい？（Chrome / Safari / Firefox DE）

**Comment by Iruyan-Zak** [comment]
4重ネストはまあ・・・
んまあ、3重ネストまでは変わってくれるなら重大な問題ではなさそう

**Comment by yamasy1549** [comment]
うぇいうぇい

**Comment by yamasy1549** [comment]
https://github.com/yamasy1549/ZinkeN/commit/24cf68b4cf75602b570c60c775170418be70c20d
