### ISSUE TITLE
段組分割

### ISSUE THREAD

**Issue by yamasy1549** [yamasy1549/ZinkeN#8]

**Comment by yamasy1549** [comment]
![image](https://cloud.githubusercontent.com/assets/7820884/15096443/b978e202-1532-11e6-92cd-2340cbf875cb.png)

楽勝でわらった

**Comment by Iruyan-Zak** [comment]
段組と段組の間隔とか、段組の範囲(図だけ～)とかは適当にCSS書いたり、適当なタグで括ったりしたらできるんだよね？

**Comment by yamasy1549** [comment]
間隔はclassではサポートしてないけどユーザーさんが直書きできるよ

e.g.:

```
        .page
          div.col-2(style="column-gap:2em;")
            figure
              img(src="./images/nfet.png")
              figcaption.fig n チャネル型 FET
            figure
              img(src="./images/pfet.png")
              figcaption.fig p チャネル型 FET

```

https://developer.mozilla.org/ja/docs/Web/Guide/CSS/Using_multi-column_layouts
